changelog:
  categories:
    - title: Launchers
      labels:
        - launcher
        - autopilot
    - title: Fixes
      labels:
        - bug
    - title: Docs
      labels:
        - documentation
    - title: Other
      labels:
        - "*"
